#!/bin/bash

#######################################################################
#Autor: Guilherme Mello Oliveira                                      #
#Date: August-2014                                                    # 
#Description: Simple script to download mp3 music from youtube        #
#             You can download a single link or put as many links     #
#             you want into a file and downloads those links.         #
#                                                                     # 
#Usage: youtube2mp3.sh [options] [link][file]                         #
#                                                                     #
#       Description: Simple script to download mp3 music from youtube #
#             You can download a single link or put as many links     #
#             you want into a file and downloads those links.         #
#                                                                     #
#      -l tells the programs to download from a single link           #
#      -f tells the program to download from the links inside a file  #
#                                                                     #
#                                                                     #
#######################################################################

links=''
file=''

optstring=f:l:h

while getopts $optstring opt; do
    case $opt in
        f) 
            file=$OPTARG
            youtube-dl -citw --extract-audio --audio-format mp3 --audio-quality 320k -a $file
            ;;
        l)
            links=$OPTARG
            youtube-dl -t --extract-audio --audio-format mp3 --audio-quality 320k $links
            ;;
        h)
            echo "youtube2mp3 -l url -f file"
            echo -e "-l expect a valid youtube url \n
                  -f expect a file containg valid youtube urls"
            ;;

    esac
done














